class FailedProcessError(Exception):

    def __init__(self):
        pass